name: rec-user-modeling
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.9
  - numpy=2.3.0
  - pandas=2.3.0
  - scikit-learn=1.7.0
  - scipy=1.15.3
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - pyyaml=6.0.2
  - tqdm=4.67.1
  - pip=24.3.1
  - pip:
    - ipykernel 


# Python version: 3.12.9
# Exported through: pip list | grep -E "numpy|pandas|scikit-learn|scipy|matplotlib|seaborn|PyYAML|tqdm"
# matplotlib      3.10.3
# numpy           2.3.0
# pandas          2.3.0
# PyYAML          6.0.2
# scikit-learn    1.7.0
# scipy           1.15.3
# seaborn         0.13.2
# tqdm            4.67.1